Vn adding bandit parser to lintly
grantmcconnaughey/Lintly pull request #42
Opened 2021-01-08 01:15 UTC by nandusekarv10

2021-01-11 19:59 UTC, grantmcconnaughey requested changes

2021-01-11 19:59 UTC, grantmcconnaughey commented on lintly/parsers.py
> +    print("Debug line before entering code")
Please remove print function.

2021-01-11 19:59 UTC, grantmcconnaughey commented on lintly/parsers.py
> +       print(output)
Please remove print function.

2021-01-11 19:59 UTC, grantmcconnaughey commented on deploy.sh
> +#twine upload dist/*
This should not be commented out or else deployment won't work anymore.

2021-01-11 19:59 UTC, grantmcconnaughey commented on lintly/parsers.py
> +        pprint(output)
Remove

2021-01-11 19:59 UTC, grantmcconnaughey commented on lintly/parsers.py
> +        while output.startswith('[main]'):
Why is this change necessary? Also please stick with 4 character indentation.

2021-01-11 22:45 UTC, nandusekarv10 commented
I created this my mistake and closing it. It is not done yet. I am trying to write a parser for Bandit as you guys wrote for pylint and other tools. Can you guide me little how can I test it locally when I will make changes?

2021-01-12 17:00 UTC, scriptsrc commented
@nandusekarv10  - You should be able to make this a "Draft" PR while you're still working on it.

2021-01-12 18:05 UTC, closed without merging